### ISSUE TITLE
wher jenny mod

### ISSUE THREAD

**Issue by sniperfoxeh** [Nrmot-GithubRepo/Project-CBT#13]
[N] Issue
[Y] Feature Request

Describe here:
 jenny mod not in modpack
Affected Items:
 jenny mod
----------------------------
Modpack Version: i havent used it yet so i dont know
Evidence: i looked through mods, no jenny mod
Culprit Items:  jenny mod
----------------------------
OptiNOTfine installed? [N]
----------------------------
Computer Specs [Optional]: rtx 3060, 32 gb of ram (like i wanna do to jenny mod), i5 11400 2.60 ghz, no jenny mod
Operating System [Optional]: windows 9
----------------------------

Please add a label according to the issue.
 jenny mod

**Comment by sniperfoxeh** [comment]
HOW DO I LABEL THINGS

**Comment by Ministry-of-CBT** [comment]
Fuck i realized only collaborators can label the issue

But anyways is tehre an official curseforge page for jenny mod?

**Comment by sniperfoxeh** [comment]
im sure this isnt a virus
https://minecraft.curseforge.com/forums/modding-java-edition/java-mods/269860-jenny-mod-1-12-2-for-minecraft-download-now-in

**Comment by Ministry-of-CBT** [comment]
- no curseforge page
- github probably took down the mod 

it appears the download link leads to a dead end.

**Comment by sniperfoxeh** [comment]
this is so sad

**Comment by Ministry-of-CBT** [comment]
aight i obtained jenny mod through trial and error

by searching the uploader's github profile 

https://github.com/GBWhatsPro/Files/tree/main/Jenny%20Mod/Files

**Comment by Ministry-of-CBT** [comment]
if my game crashes due to jenny mod being funny i will probably not add it

**Comment by Ministry-of-CBT** [comment]
WHAT IS THIS AND HOW DO I GET RID OF IT

[21:16:16] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  KonkreteCore (konkrete_forge_1.5.3_MC_1.12-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  FMCore (fancymenu_forge_2.12.6_MC_1.12-1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
  LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
  MixinBooter (!mixinbooter-8.3.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
  AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.20.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
  GregTechLoadingPlugin (gregtech-1.12.2-2.7.2-beta.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.5.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
  Loading Progress Bar Plugin (Loading-Progress-Bar-v1.0-mc[1.8-1.12.2].jar)
Contact their authors BEFORE contacting forge
// Don't be sad, have a hug! <3
Time: 8/4/23 9:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SchnurriTV's Sexmod (sexmod)
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 122!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:106)
	at com.schnurritv.sexmod.cA.func_70088_a(cA.java)
	at net.minecraft.entity.Entity.<init>(Entity.java:217)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21)
	at com.schnurritv.sexmod.bi.<init>(bi.java)
	at com.schnurritv.sexmod.cC.<init>(cC.java)
	at com.schnurritv.sexmod.cA.<init>(cA.java)
	at com.schnurritv.sexmod.ClientProxy.initRegistries(ClientProxy.java)
	at com.schnurritv.sexmod.Main.init(Main.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_345, IBM Corporation
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220817_464 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - e361c66299 based on jdk8u345-b01), Eclipse OpenJ9
	Memory: 2052013968 bytes (1956 MB) / 5102895104 bytes (4866 MB) up to 14680064000 bytes (14000 MB)
	JVM Flags: 6 total; -Xoptionsfile=C:\Users\User\AppData\Roaming\.minecraft\openjdk\jdk8u345-b01-jre\bin\default\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx14000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	| State | ID                    | Version                             | Source                                                      | Signature                                |
	|:----- |:--------------------- |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2                              | minecraft.jar                                               | None                                     |
	| LCHI  | mcp                   | 9.42                                | minecraft.jar                                               | None                                     |
	| LCHI  | FML                   | 8.0.99.99                           | forge-1.12.2-14.23.5.2860-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                 | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | micdoodlecore         | 4.0.5                               | minecraft.jar                                               | None                                     |
	| LCHI  | mixinbooter           | 8.3                                 | minecraft.jar                                               | None                                     |
	| LCHI  | foamfixcore           | 7.7.4                               | minecraft.jar                                               | None                                     |
	| LCHI  | moresoundconfigcore   | 1.0.0                               | minecraft.jar                                               | None                                     |
	| LCHI  | advancementplaques    | 1.4.10                              | AdvancementPlaques-1.12.2-1.4.10.jar                        | None                                     |
	| LCHI  | ambience              | 1.7.8                               | Ambience-1.12.2-1.7.8.jar                                   | None                                     |
	| LCHI  | appliedenergistics2   | rv6-stable-7-extended_life-v0.55.20 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.20.jar | None                                     |
	| LCHI  | galacticraftcore      | 4.0.5                               | Galacticraft-1.12.2-4.0.5.jar                               | None                                     |
	| LCHI  | galacticraftplanets   | 4.0.5                               | Galacticraft-1.12.2-4.0.5.jar                               | None                                     |
	| LCHI  | asmodeuscore          | 0.0.30                              | AsmodeusCore-1.12.2-0.0.31.jar                              | None                                     |
	| LCHI  | attributefix          | 1.0.12                              | AttributeFix-Forge-1.12.2-1.0.12.jar                        | None                                     |
	| LCHI  | jei                   | 4.25.0                              | HadEnoughItems_1.12.2-4.25.0.jar                            | None                                     |
	| LCHI  | quark                 | r1.6-179                            | Quark-r1.6-179.jar                                          | None                                     |
	| LCHI  | autoreglib            | 1.3-32                              | AutoRegLib-1.3-32.jar                                       | None                                     |
	| LCHI  | battletowers          | 1.6.5                               | BattleTowers-1.12.2.jar                                     | None                                     |
	| LCHI  | baubles               | 1.5.2                               | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LCHI  | betteradvancements    | 0.1.0.77                            | BetterAdvancements-1.12.2-0.1.0.77.jar                      | None                                     |
	| LCHI  | bettercaves           | 1.12.2                              | bettercaves-1.12.2-2.0.4.jar                                | None                                     |
	| LCHI  | bettermineshafts      | 1.12.2-2.2.1                        | BetterMineshaftsForge-1.12.2-2.2.1.jar                      | None                                     |
	| LCHI  | bnbgaminglib          | 2.17.6                              | BNBGamingLib-1.12.2-2.17.6.jar                              | None                                     |
	| LCHI  | carryon               | 1.12.3                              | carryon-1.12.2-1.12.7.23.jar                                | None                                     |
	| LCHI  | chameleon             | 1.12-4.1.3                          | Chameleon-1.12-4.1.3.jar                                    | None                                     |
	| LCHI  | clumps                | 3.1.2                               | Clumps-3.1.2.jar                                            | None                                     |
	| LCHI  | codechickenlib        | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | collective            | 3.0                                 | collective-1.12.2-3.0.jar                                   | None                                     |
	| LCHI  | cosmeticarmorreworked | 1.12.2-v5a                          | CosmeticArmorReworked-1.12.2-v5a.jar                        | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHI  | customfov             | 1.12.2-1.0.1                        | customfov-1.12.2-1.0.1.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | customloadingscreen   | 1.12.2-1.5.7                        | CustomLoadingScreen-1.12.2-1.5.7.jar                        | None                                     |
	| LCHI  | customwindowtitle     | 1.0.0                               | CustomWindowTitle-Legacy-v1.0.0.jar                         | None                                     |
	| LCHI  | dynamictrees          | 1.12.2-0.9.29                       | DynamicTrees-1.12.2-0.9.29.jar                              | None                                     |
	| LCHI  | waila                 | 1.8.26                              | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
	| LCHI  | tfc                   | 1.7.23.181                          | TerraFirmaCraft-MC1.12.2-1.7.23.181.jar                     | None                                     |
	| LCHI  | dynamictreestfc       | 0.9.17                              | dynamictreestfc-0.9.17.jar                                  | None                                     |
	| LCHI  | enchdesc              | 1.1.20                              | EnchantmentDescriptions-1.12.2-1.1.20.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | energyconverters      | 1.3.7.30                            | energyconverters_1.12.2-1.3.7.30.jar                        | None                                     |
	| LCHI  | forgelin              | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
	| LCHI  | mantle                | 1.12-1.3.3.55                       | Mantle-1.12-1.3.3.55.jar                                    | None                                     |
	| LCHI  | tconstruct            | 1.12.2-2.13.0.183                   | TConstruct-1.12.2-2.13.0.183.jar                            | None                                     |
	| LCHI  | exnihilocreatio       | 1.12.2-0.4.7.2                      | exnihilocreatio-1.12.2-0.4.7.2.jar                          | None                                     |
	| LCHI  | mjrlegendslib         | 1.12.2-1.2.1                        | MJRLegendsLib-1.12.2-1.2.1.jar                              | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | zollerngalaxy         | 2.0.45                              | ZollernGalaxy-1.12.2-2.0.45.jar                             | None                                     |
	| LCHI  | extraplanets          | 1.12.2-0.7.6                        | ExtraPlanets-1.12.2-0.7.6.jar                               | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | konkrete              | 1.5.3                               | konkrete_forge_1.5.3_MC_1.12-1.12.2.jar                     | None                                     |
	| LCHI  | fancymenu             | 2.12.6                              | fancymenu_forge_2.12.6_MC_1.12-1.12.2.jar                   | None                                     |
	| LCHI  | fastfurnace           | 1.3.1                               | FastFurnace-1.12.2-1.3.1.jar                                | None                                     |
	| LCHI  | fastbench             | 1.7.4                               | FastWorkbench-1.12.2-1.7.4.jar                              | None                                     |
	| LCHI  | firstjoinmessage      | 1.2                                 | firstjoinmessage_1.12.2-1.2.jar                             | None                                     |
	| LCHI  | foamfix               | @VERSION@                           | foamfix-0.10.15-1.12.2.jar                                  | None                                     |
	| LCHI  | ftbbackups            | 1.1.0.1                             | FTBBackups-1.1.0.1.jar                                      | None                                     |
	| LCHI  | ftblib                | 5.4.7.2                             | FTBLib-5.4.7.2.jar                                          | None                                     |
	| LCHI  | ic2                   | 2.8.222-ex112                       | industrialcraft-2-2.8.222-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | itemfilters           | 1.0.4.2                             | ItemFilters-1.0.4.2.jar                                     | None                                     |
	| LCHI  | ftbquests             | 1202.9.0.15                         | FTBQuests-1202.9.0.15.jar                                   | None                                     |
	| LCHI  | galaxyspace           | 2.0.19                              | GalaxySpace-1.12.2-2.0.19.jar                               | None                                     |
	| LCHI  | gregtech              | 2.7.2-beta                          | gregtech-1.12.2-2.7.2-beta.jar                              | None                                     |
	| LCHI  | gcym                  | 1.2.4                               | GregicalityMultiblocks-1.2.4.jar                            | None                                     |
	| LCHI  | gregtechfoodoption    | @VERSION@                           | gregtechfoodoption-1.9.3.1.jar                              | None                                     |
	| LCHI  | hardcoredarkness      | 2.0                                 | HardcoreDarkness-MC1.12.2-2.0.jar                           | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHI  | hardcorerevival       | 1.2.0                               | HardcoreRevival_1.12.2-1.2.0.jar                            | None                                     |
	| LCHI  | infinitenight         | 1.0.0                               | innight-1.0.jar                                             | None                                     |
	| LCHI  | innight               | 1.0                                 | innight-1.0.jar                                             | None                                     |
	| LCHE  | sexmod                | 1.9.0                               | Jenny-Mod-Forge-1.12.2-v1.9.0 (1).jar                       | None                                     |
	| LCH   | geckolib3             | 3.0.30                              | Jenny-Mod-Forge-1.12.2-v1.9.0 (1).jar                       | None                                     |
	| LCH   | jeid                  | 1.0.4-SNAPSHOT                      | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar                       | None                                     |
	| LCH   | legendarytooltips     | 1.1.9                               | LegendaryTooltips-1.12.2-1.1.9.jar                          | None                                     |
	| LCH   | letmedespawn          | 1.0                                 | letmedespawn-1.12.2-forge-1.0.2.jar                         | None                                     |
	| LCH   | lpb                   | 1.0                                 | Loading-Progress-Bar-v1.0-mc[1.8-1.12.2].jar                | None                                     |
	| LCH   | loadingprofiler       | 1.1                                 | LoadingProfiler-MC1.12-1.3.jar                              | None                                     |
	| LCH   | loadingscreens        | 0.3.1                               | LoadingScreens-1.12.2-0.3.1.jar                             | None                                     |
	| LCH   | loadmyresources       | 1.0.1                               | loadmyresources_1.0.1_MC_1.12-1.12.2.jar                    | None                                     |
	| LCH   | stevekung's_lib       | 1.3.0                               | SteveKunG's-Lib-mc1.12.2-v1.3.0.jar                         | None                                     |
	| LCH   | moreplanets           | 2.3.2                               | More-Planets-1.12.2-2.3.2-GC4.0.5.jar                       | None                                     |
	| LCH   | moreplayermodels      | 1.12.2                              | MorePlayerModels_1.12.2-(05Dec19).jar                       | None                                     |
	| LCH   | hbm                   | NTM-Extended-1.12.2-1.9.7           | NTM-Extended-1.12.2-1.9.7.jar                               | None                                     |
	| LCH   | nuclearoption         | 2.6                                 | NuclearOption-1.12-2.6.jar                                  | None                                     |
	| LCH   | patchouli             | 1.0-23.6                            | Patchouli-1.0-23.6.jar                                      | None                                     |
	| LCH   | reachfix              | 1.0.9                               | ReachFix-1.12.2-1.0.9.jar                                   | None                                     |
	| LCH   | refinedstorage        | 1.6.16                              | refinedstorage-1.6.16.jar                                   | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | resourceloader        | 1.5.3                               | ResourceLoader-MC1.12.1-1.5.3.jar                           | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bettercombatmod       | 2.0.8                               | RLCombat-1.12.2-2.0.8.jar                                   | None                                     |
	| LCH   | silentlib             | 3.0.13                              | SilentLib-1.12.2-3.0.14+168.jar                             | None                                     |
	| LCH   | scalinghealth         | 1.3.37                              | ScalingHealth-1.12.2-1.3.42+147.jar                         | None                                     |
	| LCH   | silentgear            | 0.6.5                               | SilentGear-1.12.2-0.6.7+76.jar                              | None                                     |
	| LCH   | silentgems            | 2.8.18                              | SilentsGems-1.12.2-2.8.22+327.jar                           | None                                     |
	| LCH   | silentgemstic         | 0.1.1                               | SilentsGems-TiC-1.12.2-0.1.1-5.jar                          | None                                     |
	| LCH   | spartanweaponry       | 1.5.3                               | SpartanWeaponry-1.12.2-1.5.3.jar                            | None                                     |
	| LCH   | srparasites           | 1.9.12                              | SRParasites-1.12.2v1.9.12.jar                               | None                                     |
	| LCH   | stg                   | 1.12.2-1.2.3                        | stg-1.12.2-1.2.3.jar                                        | None                                     |
	| LCH   | storagedrawers        | 5.5.0                               | StorageDrawers-1.12.2-5.5.0.jar                             | None                                     |
	| LCH   | tfcthings             | 1.3.5                               | terrafirmathings-1.3.5.jar                                  | None                                     |
	| LCH   | texfix                | 4.0                                 | TexFix V-1.12-4.0.jar                                       | None                                     |
	| LCH   | touhou_little_maid    | 1.2.5                               | touhoulittlemaid-1.12.2-1.2.5-release.jar                   | None                                     |
	| LCH   | moresoundconfig       | 1.0.4                               | moresoundconfig-1.0.4.jar                                   | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	Loaded coremods (and transformers): 
SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  pl.asie.splashanimation.core.SplashProgressTransformer
KonkreteCore (konkrete_forge_1.5.3_MC_1.12-1.12.2.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
FMCore (fancymenu_forge_2.12.6_MC_1.12-1.12.2.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
  ichttt.mods.moresoundconfig.asm.MSCTransformer
LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
  alexiil.mc.mod.load.coremod.ClsTransformer
MixinBooter (!mixinbooter-8.3.jar)
  
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
  org.dimdev.jeid.JEIDTransformer
AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.20.jar)
  appeng.core.transformer.AE2ELTransformer
ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
  
GregTechLoadingPlugin (gregtech-1.12.2-2.7.2-beta.jar)
  gregtech.asm.GregTechTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
MicdoodlePlugin (Galacticraft-1.12.2-4.0.5.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
  
Loading Progress Bar Plugin (Loading-Progress-Bar-v1.0-mc[1.8-1.12.2].jar)
  git.jbredwards.lpb.Main$Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.49' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7-extended_life-v0.55.20 for Forge 14.23.5.2847
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)
	Patchouli open book context: n/a
[21:16:16] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\User\AppData\Roaming\PrismLauncher\instances\PROJECT CBT DEV UNOFFICIAL\minecraft\crash-reports\crash-2023-08-04_21.16.16-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Ministry-of-CBT** [comment]
aight let it be known that THERE WILL BE no more jenny mod, BECAUSE jenny mod conflicting with one of the mods in the pack.

**Comment by sniperfoxeh** [comment]
😭

**Comment by RealRainbuu** [comment]
we need to make a custom marisa sex mod

**Comment by Nrmot** [comment]
lets see if anyone is willing to code a marisa sex mod and hope it's not shot down by github or curseforge or whatever platform the mod is gonna be hosted from :trollface:

**Comment by fahimtaunsvi** [comment]
[Jenny Mod](https://jennymodx.com/) (Fapcraft) adds a “girlfriend” character to the game who can engage with the player like a real girl. It is a mod that only works in “Creative” mode and is gaining more popularity among users. The players are able to purchase various services from Jenny using in-game currencies, which play out with bespoke animations. It’s also only available in the PC version, so there’s no risk of exposure for Xbox, PlayStation, Nintendo Switch, Android, and iOS users.
