### ISSUE TITLE
Add additional backup solution mod

### ISSUE THREAD

**Issue by KorewaLidesu** [Nrmot-GithubRepo/Project-CBT#16]
[N] Played this modpack?
[N] OptiNOTFine?
[N] Issue
[Y] Feature Request
[N] Lore issue?

Modpack Version: (if any)
Ignored
Issue/Feature Request:
Add additional backup solution for world since FTB Backup have issue where backup dont sync properly between player inv and world (player inv is sync properly while world is backup before that a few minutes ~~can be hours at worse~~)
Affected Items:
Ignored
Culprit Items:
Ignored
Evidence:
No evidence as it was from private smp (Ignored)
Solution:

**Comment by Nrmot** [comment]
Okay so which other backup mod to use instead?


if ftb backups has issues then....

**Comment by quentin452** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-backups

**Comment by Nrmot** [comment]
-Curseforge Page [Yes]
-1.12.2 support [Yes]

Accepted
