### ISSUE TITLE
What is permanight and how do I get rid of it

### ISSUE THREAD

**Issue by TehDrpStr** [Nrmot-GithubRepo/Project-CBT#21]
[Y/N] Played this modpack? Y
[Y/N] OptiNOTFine? N
[Y/N] Issue ?
[Y/N] Feature Request ?Y
[Y/N] Lore issue? N

Modpack Version: (if any)
dev10
Issue/Feature Request:
how do you get rid of permanight? its constantly midnight and i cant
Affected Items:
me
Culprit Items:
me
Evidence:
the moon is not moving and i cant see anything
Solution:
getting rid of it
[if bug/crash] Error Messages: 

Put Your Issue Label here: 
how do i get rid of it
Optional: [Computer Specs, OS version]

**Comment by Higuys153** [comment]
thats the point

**Comment by Higuys153** [comment]
did you even read the readme

**Comment by Nrmot** [comment]
infinite night mod causes the permanent nighttime mod.

I guess you can safely remove that server side mod but it's included in the modpack by default and its part of the experience

**Comment by Nrmot** [comment]
Issue has been closed

Infinite night is part of the default experience because its project cock and ball torture

**Comment by Higuys153** [comment]
(you can use night vis btw)

**Comment by Nrmot** [comment]
Pin of torture
