### ISSUE TITLE
nrmot do you have a discord?

### ISSUE THREAD

**Issue by Lrdmtns** [Nrmot-GithubRepo/Project-CBT#24]
pls if you do add lrdmtns on discord

**Comment by Nrmot** [comment]
i unfortunately don't have discord yet

but you can still contact me through reddit

**Comment by Lrdmtns** [comment]
> 

uh yeah i tried

**Comment by Lrdmtns** [comment]
im u/lrdmtns

**Comment by Nrmot** [comment]
aight i already sent a message through reddit, accepted chat request
