### ISSUE TITLE
add furries

### ISSUE THREAD

**Issue by Anthonity** [Nrmot-GithubRepo/Project-CBT#25]
[Y/N] Played this modpack? no
[Y/N] OptiNOTFine? no
[Y/N] Issue no
[Y/N] Feature Request yes
[Y/N] Lore issue? stfu

Modpack Version: the second one
Issue/Feature Request: add furry

Affected Items:

Culprit Items:

Evidence:

Solution:

[if bug/crash] Error Messages: 

Put Your Issue Label here: 

Optional: gtx 1069 + intel i9 6969 + 16.9 gb of ram

**Comment by Nrmot** [comment]
is there a curseforge mod that adds furries?

**Comment by Higuys153** [comment]
i believe so let me check

**Comment by Higuys153** [comment]
couldnt find anything for 1.12 unfortunatly

**Comment by Nrmot** [comment]
Ahhhhhhhh ok

**Comment by Anthonity** [comment]
tails mod

**Comment by Higuys153** [comment]
@Nrmot [https://www.curseforge.com/minecraft/mc-mods/tails](url)

**Comment by Nrmot** [comment]
Okay

**Comment by Nrmot** [comment]
i will add this later once i come back from school
