### ISSUE TITLE
im going to learn groovyscript just to make absolute bullshit recipe changes

### ISSUE THREAD

**Issue by Nrmot** [Nrmot-GithubRepo/Project-CBT#27]
you can't stop me now

i will attempt to add the crazy recipes such as this one:

![2023-08-09_17 42 00](https://github.com/Nrmot-GithubRepo/Project-CBT/assets/141803157/9cfe31e8-7046-4d62-b26f-c495dd24ba45)

**Comment by Higuys153** [comment]
pretty

**Comment by Higuys153** [comment]
i believe you need crafttweaker

**Comment by Higuys153** [comment]
wtf is tetraschrabadic_trinaquadium

**Comment by Nrmot** [comment]
4-schrabidium
3-naquadah

also i used groovyscript to add that item ingame

**Comment by Nrmot** [comment]
also new circuit crafting plan using avaritia's extreme crafting:

with this as a baseline:

tetraschrabadic trinaquadium single horizontal wire
tetraschrabadic trinaquadium single vertical wire
tetraschrabadic trinaquadium single 4way crosswire
tetraschrabadic trinaquadium single tri-joint wire pos1
tetraschrabadic trinaquadium single tri-joint wire pos2
tetraschrabadic trinaquadium single tri-joint wire pos3
tetraschrabadic trinaquadium single tri-joint wire pos4
tetraschrabadic trinaquadium single cornered wire
tetraschrabadic trinaquadium double horizonal wire
tetraschrabadic trinaquadium double vertical wire
tetraschrabadic trinaquadium double-single 4way cross wire
tetraschrabadic trinaquadium double 4way cross wire
tetraschrabadic trinaquadium double cornered wire
tetraschrabadic trinaquadium double-single cornered wire
tetraschrabadic trinaquadium single-double tri-joint wire pos1
tetraschrabadic trinaquadium single-double tri-joint wire pos2
tetraschrabadic trinaquadium single-double tri-joint wire pos3
tetraschrabadic trinaquadium single-double tri-joint wire pos4
tetraschrabadic trinaquadium double tri-joint wire pos1
tetraschrabadic trinaquadium double tri-joint wire pos2
tetraschrabadic trinaquadium double tri-joint wire pos3
tetraschrabadic trinaquadium double tri-joint wire pos4

tridaffergon dieuphenium circuit plating
tridaffergon dieuphenium circuit seperators

totally a good idea to add in the game
