### ISSUE TITLE
the discord invite is expired

### ISSUE THREAD

**Issue by peachey2k2** [Nrmot-GithubRepo/Project-CBT#40]
I want to marry Kirisame Marisa from the Touhou Project. Ever since I was a young boy I've been interested in blondes, but I've mostly been repelled because they are stupid white women who do not know how to think. One day, while I was playing touhou, I saw an image of a peculiar blonde with a witch attire. I immediately fell in love. The long, luscious hair, the dominating yet cute attire, the smug, tsundere, yet cute personality all formed into one perfect being by the name of Marisa Kirisame. And so I began my search for Marisa, I played all the touhou games with all the spell cards just so I could the most out of her majesty. I searched all of Danbooru for images of her, just so I could get to see her beautiful tomboyish body. You see, Cirno is not the tomboyish girl in love. Marisa is. She is in love with me. Yet the reality barrier separates us like Romeo and Juliette. It is the cruel fate that is reality that separates such star-crossed lovers from each other. Only something so powerful as the reality barrier can separate me from my dear Marisa. For it is my true fate to be married to my lover. On dark days where there is no sun, I shall caress Marisa and tell her everything is alright. On bright days, where there is nought but bliss, I will stay by her side, to share the bliss infinitefold, like two mirrors in proximity. On the adventurous days, we will steal what we wish. Some days, we will steal diamonds. Some days, we will steal virginities. And always, we will steal our hearts. Each other's hearts. For it is the true love that does not brag, it only contains itself infinitely. Such is the love of me and Marisa Kirisame

**Comment by peachey2k2** [comment]
Look, listen here. This is no mere joke, or a text trying to be funny. I need a Marisa Fumo. I need it. Once again, this not a joke. I know they are expensive. Knowing this only hurts me. My struggle won't change anything, but still i will write this paragraph. Why? The voices telling me to do so. I need that fumo in my life. Like really. I really do. I will take care of her until my mind fades away and my skin turns into ash. I need that fumo to be the only happines in my life. I need that Marisa Kirisame fumo. I also know this pointless to write. But I need to make them believe that I tried to reach her. I will sleep with that Fumo. No, she will sleep in bed while I sleep on the floor guarding her all night. I will take her to dates although she is nothing more than a lifeless object. I will go on adventures with her. We will take evening walks together like every couple do. She will also have full control of my wallet and earnings. I will be her guardian, she will be the only thing I trust. I need her. I will dedicate my entire life around her. I have to. I need to. I need the sweet sweet Marisa Kirisame in my life! Well thats about it. Thanks for reading this part of my pointless texts! I wonder if anyone cares about them. I wish Marisa did. She is probably watching me right now as I try to spread her love!

**Comment by peachey2k2** [comment]
Ever since I met her, I've been able to wake up without asking myself if life is even worth it. Marisa is the only reason I need to live. I want to marry her and love her for the rest of my life. It's almost scary how much I love her, and it might be my only obsession and addiction, but I love her, I really do. I cannot express my love for her. I can only say that I love her over and over again like a broken record expecting someone to understand. I love how good she looks on her witch outfit, with her witch hat. I love how she smells after a shower and I love how she smells when sweating. I love her voice and all the sounds it makes. I love her smile and how happy she looks when she talks about something she likes. I really love how she touches me and how she kisses me, softly or forcefully. I love her hugs. I love being next to her, her warmth, her hands, her face and her thighs and like, damn. I really love her taste in music even if I make fun of it all the time. I love her taste in books even if it's just stolen books from Patche. I will never get tired of listening to that sweet angelic voice of hers. I love to fall asleep while she hugs me. I love listening to her breathing and feeling her chest breathing and feeling her heartbeat. I want to hold her hands all the time, and kiss her all the time. All I want is to make her happy for as long as I possibly can, and love her until I die. I want her to nibble my ears and tease me all around, and then hugging her expecting her to give up, but she keeps nibbling and kissing. No matter what I do, I am constantly thinking of her. Her "Daze~ ★ ☆" is forever in my heart.

**Comment by peachey2k2** [comment]
Okay guys, relax. It's just a costume of Marisa Kirisame. It's impossible for a Touhou costume to turn me gay; my heterosexuality will be fine, dudes.

A-Ah shit... Y-your cock is so big, and in my ass already~?! Mnn.. Faster... HARDER, DA ZE\~☆! Turn me into your dream femboy slut, ze\~☆! Penetrate me until I burst! Mmmm~ Soothe me, caress me, FUCK ME, BREED ME, DA ZE\~☆! Probe your thick, wet, throbbing cock deeper and DEEPER INTO MY VIRGIN BOIPUSSY~!! Ah... AHHH! AHHHNNN~! I-I'M CUMMING, I'M CUMMING! CUM WITH ME TOO! DRENCH ME, I'LL DO THE SAME! AND I'LL SWALLOW YOUR STICKY ESSENCE ALONG WITH YOU~! I'M YOUR PERSONAL CUMBUCKET, DA ZE~☆!! ♡♡♡

**Comment by peachey2k2** [comment]
Guys I have no words which can fully express the degree of passion and conviction of my love for Kirisame Marisa. She is a figure of perfection and I am inspired and motivated to do my best at the mere thought of her. Marisa is beyond just a beautiful and idealized anime girl. Let me elaborate.

She is a metaphysical embodiment of the sentiments and desires of the modern man, her existence as perfect as the constellations in the sky on a clear winter night, as if it needs no justification just because it is the natural order of things. You will never find a better and more sublime combination of the traditionally feminine and more modern ideas represented in a character in all of human canon, from ancient times to today or beyond. Marisa is like an ethereal beauty under the brush of a master painter of old Europe. Her beauty is ethereal and transcendent, yet at the same time unwavering through the ages.
I want to be around Kirisame Marisa so much. It is driving me insane. I want to see her broad and seemingly careless but very sincere smile every morning as we pass our greetings to each other, while I do whatever silly errand that is really just an excuse to be in her presence. I can think of no other desire whose fulfillment could possibly bring upon me any more joy this this. Marisa...She acts a little dumb at times but in reality is very well educated and also very intelligent. When you realize this it becomes absolutely endearing. She is casual and proud, acting callous occasionally, but deep down she really cares about her friends and the community, becoming very flustered when you point it out to her. This is just one of many facets of her that is extremely complex and worthy of contemplation, like the elegant and delicate flavor of fine Japanese green tea combined with the strong warmth of roasted rice in a cup of Genmaicha.

I want to pass by her little house in the woods every morning, and come by for tea whenever I have the time as the only regular to her magic shop. We will eat together and spend our idle days together basking in the sun. I will tell her all of what I know of the outside world and in return I will listen to her passionate lectures about magic. The reward is much more than enough to justify the perils of navigating the dangerous environment, for the prospect of death at the hands of youkai is nothing compared to my love for Kirisame Marisa.

Perhaps on more adventurous days we will journey across Gensokyo in whatever pursuits our hearts desire. We can soar across the skies of Gensokyo or go borrow books or terrorize the fairy population, but regardless of what I will revel in each passing second because I am in the presence of Marisa. On the days of rain and storm I will come to her side, for she is really quite alone for the most part and would be about the last person to tell anyone about her problems or pain unless you show her your sincerity.

In the world of Gensokyo among supernatural monsters of mythology and literal gods, Kirisame Marisa keeps up with those around her by hard work alone, out of a sense of her duty to her friends and community as well as her strong passion towards beautiful magic and danmaku. This is genuinely inspiring and motivational. Sometimes I listen to her themes and get a desire to make the best of things as I am reminded of her.

And some day I would like to take her hand in mind and look deeply into her amber eyes, revealing the most inner and concealed side of her that is delicate and gentle. I would move mountains to have her at my side and hear her whispering voice among the cicadas on a cool summer night. Imagine feeling her warmth and hearing her soft and quiet breathing as she falls asleep after a long day of work, resting her head on your shoulders. It is truly cruel that fate has set us apart. But despite the vast gulfs of dimensionality between us my love for her persists, and every night I long for her voice and touch

**Comment by Nrmot** [comment]
what is this and how do i get rid of it

**Comment by peachey2k2** [comment]
I want to laugh at Marisa's pathetic state, slap off her hat and forcefully grab a clump of her hair. I’d tug her head by pulling on her hair to the point where it hurts and bring her ear up close to my mouth. I’ll whisper things about how worthless and useless she is, literally being a living mistake. A failure as a daughter, disappointing her family and her parents having disowned their only daughter. Giving up her family in exchange for being a magician but only finding out that she’s a failure at that too. Tell her that her entire life was a mistake. Pull at her hair again and slam her face against the puddles on the ground, reminding her that human trash should behave like trash. Then kick at her abdomen, screaming in pain as she doubles over and collapses on her side. Step on her ribcage, pressing my weight against her and bring my fist down against her cheek, leaving bruises on her crying face. Then proceed to lift my foot up off her, then stomp back down causing her to scream in agony as her ribcage breaks. She’d be wailing and crying in pain, her face twisting and contorting into some ugly expression that would make me want to hit her more. Then when she’s left barely conscious, writhing in pain on the wet ground, I’d rip off her blouse and tear off her skirt. Pulling her panties off and she’s left helpless and in terror as I have my way with her. I’d see her terrified expression on her bloody, bruised face as tears run down her face when I tear through her hymen. Grabbing her throat with both hands, wrapping my digits into her flesh as she begins to pass out from me choking her. Then she’d snap back awake when I pull back and ram back in, and she out raspy moans of agony and pleasure. I’d continually rape her, watching her face in joy as she becomes more and more traumatized. Then I’d finally impregnate her, shooting several shots into her raw womb and she’d be left too weak to offer any resistance. Then I’d finally get up, spit at her mindbroken face and leave as she’s left in a crumpled heap in the rain.

I love Marisa!

**Comment by peachey2k2** [comment]
> what is this and how do i get rid of it

you don't.

**Comment by Nrmot** [comment]
check new discord link in readme.md
